events {}

http {

  upstream backend_servers {
      server server:3000;
  }

  server {
      listen 8080 ssl;

      ssl_certificate /etc/nginx/certs/localhost.pem;
      ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

      location / {
          proxy_pass http://client:5173;
      }

      location /api {
          proxy_pass http://server:3000;
      }
  }

}